# Generated by Django 5.1 on 2024-10-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_user_friends_id_user_request_received_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='like_user_id',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
