# Generated by Django 5.1 on 2024-10-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_posts_like_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='like_user_id',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
